server:
  port: 8080
key:
  public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApkpYnourkCApQGC8XEa5DO+XEpKLQ/DUkaDumyFarklkumr1polByTCGxpMEAfj9SYSbc58jbAtkHWRzsfQsJucDfW8L2Pjtx8ycHcQUfv9sQEdRgkRmn0tsOBJXX8mgE2gss+uKMU4qKwF3YqUyvoJi+MBsGJqPGbUh4QzUiwsQogZ8v67IYtm1fSq+/KA8vLnOTD+ghIDrqhlGvm4IGclK5RTX5Cax4x00bnsoOyG5tOjSDNHtOx8yhFtSLY9DoILyZPliVliwsLTSNFFRPsv2Ms/ozVpeeNz31HDTD0cFeKht6PkdJKQFnn6f4+l7gr/Gggfb7iACGUAp+KOvxwIDAQAB
  aes: ssshhhhhhhhhhh!!!!
  
service:
  creditcard:
    url: http://35.238.1.128
    
gcp:
  project-id: gothic-scheme-334505
  key-zone: us-central1
  key-ring: rsa_key_ring_asym
  key-name-rsa: rsa_key_asym
  key-version-rsa: '1' 
  
management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env
        
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} | %-5level | %logger{36} | %msg%n'